[versions]
agp = "8.7.3"
kotlin = "2.0.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
picasso = "2.71828"
spinnerdatepicker = "2.0.1"
truth = "1.4.4"
roomRuntime = "2.6.1"
roomCompiler = "2.6.1"
roomKtx = "2.6.1"
retrofit = "2.11.0"
converterGson = "2.11.0"
loggingInterceptor = "5.0.0-alpha.14"
ksp = "2.0.0-1.0.22"
hiltAndroid = "2.53.1"
glide = "5.0.0-rc01"
compiler = "5.0.0-rc01"
timber = "5.0.1"
core = "1.6.1"
hamcrest = "2.2"
coreTesting = "2.2.0"
robolectric = "4.12.1"
mockitoCore = "5.14.2"
dexmaker = "2.28.3"
coroutineTesting = "1.7.3"
lifecycleRuntimeKtx = "2.8.7"
hiltAndroidTesting = "2.51.1"
hiltAndroidCompiler = "2.53.1"
fragmentTesting = "1.8.5"
espressoContrib = "3.6.1"
navigationFragmentKtx = "2.8.5"
navigationUiKtx = "2.8.5"
mockitoAndroid = "5.12.0"
darwinsys = "1.5.1"
jakewharton = "1.3.1"
firebaseBom = "33.7.0"
firebaseMessaging = "24.1.0"
firebaseAnalytics = "22.1.2"
firebaseCrashlytics = "19.3.0"
fierbaseCrashlyicsPlugIn = "3.0.2"
appUpdate = "2.1.0"
appUpdateKtx = "2.1.0"
review = "2.0.2"
reviewKtx = "2.0.2"
googleService = "4.4.2"
firebaseAuth = "23.1.0"
datePicker = "2.0.1"
hiltCompiler = "2.54"
firebaseAuthVersion = "23.1.0"
firebaseDatabase = "21.0.0"
[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomRuntime" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomCompiler" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converterGson" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltAndroid" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltAndroid" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version.ref = "firebaseAnalytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlytics" }
spinnerdatepicker = { module = "com.github.drawers:SpinnerDatePicker", version.ref = "spinnerdatepicker" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltCompiler" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuthVersion" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }